name: Notas sobre código
markdown: redcarpet
pygments: true
highlighter: pygments
comments :
  provider : disqus
  disqus :
    short_name : anmaia
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
