# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: André Maia
email: andrenmaia@gmail.com
description: Notas sobre código é um blog que compartilha dicas e formas de programação com várias linguagens diferentes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anmaia.com.br" # the base hostname & protocol for your site

# Social usernames
email: andrenmaia@gmail.com
github_username:  andrenmaia
twitter_username: andrenmaia
linkedin_username: andrenmaia
goodreads_username: 17931907-andr-maia
stackoverflow_username: anmaia

# Permalink config
permalink: 'posts/:title'

# Build settings
markdown: redcarpet

# Redirect
# `safe `must be set false for jekyll-redirect-from
# to run in development. (Github Pages will override
# `safe` to be true on deploy, but it makes an
# exception for jekyll-redirect from.)
safe: false
gems:
  - jekyll-redirect-from


# Comment system
comments:
  provider: disqus
  disqus:
    short_name: anmaia
  livefyre:
    site_id: 123
  intensedebate:
    account: 123abc
  facebook :
    appid: 123
    num_posts: 5
    width: 580
    colorscheme: light