# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: André Maia
email: andrenmaia@gmail.com
description: Notas sobre código é um blog que compartilha dicas e formas de programação com várias linguagens diferentes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anmaia.com.br" # the base hostname & protocol for your site
twitter_username: andrenmaia
github_username:  andrenmaia
permalink: 'posts/:title'

# Build settings
markdown: redcarpet

# Redirect
gems:
  - jekyll-redirect-from