name: Notas sobre código
permalink: '/:title'
markdown: redcarpet
highlighter: pygments
defaults:
  values:
    layout: null
comments :
  provider : disqus
  disqus :
    short_name : anmaia
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
